# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 16:39
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GodzinyPrzyjec',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('miastoStartowe', models.CharField(max_length=40)),
                ('miastoKoncowe', models.CharField(max_length=40)),
                ('ulicaStartowa', models.CharField(max_length=40)),
                ('ulicaKoncowa', models.CharField(max_length=40)),
                ('nrBudynkuStartowy', models.IntegerField(max_length=10)),
                ('nrBudynkuKoncowy', models.IntegerField(max_length=10)),
                ('data', models.DateField()),
                ('odGodziny', models.IntegerField(max_length=2)),
                ('doGodziny', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('loginy', models.CharField(max_length=25, unique=True)),
                ('hasla', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('numerKonta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('nrRejestracji', models.AutoField(primary_key=True, serialize=False)),
                ('priorytet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UslugiTyp',
            fields=[
                ('typ', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('nrWizyty', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('rodzajPlatnosci', models.CharField(choices=[('po', 'Pobranie'), ('pr', 'Przelew')], default='po', max_length=2)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data', models.DateField(blank=True)),
                ('godzina', models.IntegerField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MiejsceITermin',
            fields=[
                ('miasto', models.CharField(max_length=40)),
                ('ulica', models.CharField(max_length=40)),
                ('numerBudynkuMieszkania', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('odGodziny', models.IntegerField(max_length=2)),
                ('doGodziny', models.IntegerField(max_length=2)),
                ('osoba2NerRejestracji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rejestracje.Rejestracja')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=40)),
                ('telefon', models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[0-9]{9,12}$')])),
                ('miasto', models.CharField(max_length=40)),
                ('ulica', models.CharField(max_length=40)),
                ('numerBudynkuMieszkania', models.CharField(max_length=10)),
                ('kontoNumerKonta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rejestracje.Konto')),
            ],
        ),
        migrations.AddField(
            model_name='wizyta',
            name='rejestracjaNrRejestracji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Rejestracja'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='uslugiTyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracje.UslugiTyp'),
        ),
        migrations.CreateModel(
            name='Fizjoterapeuta',
            fields=[
                ('pensja', models.DecimalField(decimal_places=2, max_digits=7)),
                ('osobaKontoNumerKonta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rejestracje.Osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('rabat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('osobaKontoNumerKonta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rejestracje.Osoba')),
            ],
        ),
        migrations.AddField(
            model_name='wizyta',
            name='fizjoterapeuta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Fizjoterapeuta'),
        ),
        migrations.AddField(
            model_name='rejestracja',
            name='pacjentOsobaKontoNumerKonta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Pacjent'),
        ),
        migrations.AddField(
            model_name='rejestracja',
            name='preferowanyFizjoterapeuta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Fizjoterapeuta'),
        ),
        migrations.AddField(
            model_name='godzinyprzyjec',
            name='ficjoterapeutaOsobaKontoNumerKonta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Fizjoterapeuta'),
        ),
    ]
