# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejestracja',
            name='preferowanyFizjoterapeuta',
        ),
        migrations.AddField(
            model_name='miejsceitermin',
            name='preferowanyFizjoterapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Fizjoterapeuta'),
        ),
        migrations.AlterField(
            model_name='uslugityp',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='fizjoterapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Fizjoterapeuta'),
        ),
    ]
