# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracje', '0002_auto_20170205_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='miejsceitermin',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miejsceitermin',
            name='osoba2NerRejestracji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracje.Rejestracja'),
        ),
    ]
